/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bht.swt.esa.tst;

public class App {

    public static void main(String[] args) {
        ACDE acde = new ACDE();
        
        int a = ACDE.romanNumeralsToNumbers("LXIX");
        System.out.println(a);
    }
}
