/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bht.swt.esa.tst;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static String getJavaVersion() {
        return System.getProperty("java.version");
    }

    public static void main(String[] args) {
        Acde acde = new Acde();
    }
}
